### ISSUE TITLE
README example doesn't use vinyl-fs

### ISSUE THREAD

**Issue by proehlen** [shinnn/gulp-svelte#1]
Couldn't get the example code snippet from the README to work but digging through the code I found I could get it to work if I piped a vinyl-fs stream to gulp-svelte.  

Assuming that's correct, I'm in the process of submitting a pull request to update the README.

**Comment by shinnn** [comment]
Thanks for the report, @proehlen.  v0.3.1 doesn't require `vinyl-fs`.
