### ISSUE TITLE
Support IIFE/UMD modules

### ISSUE THREAD

**Issue by PixievoltNo1** [shinnn/gulp-svelte#3]
Currently if you specify "iife" or "umd" for `options.format`, Svelte throws an error due to `options.name` not being present. Technically you could specify that, too, but every file in the glob would get the same name.

I'm already working on a fix for this that infers `options.name` from the filename, the same way svelte-cli does. [These are my changes so far.](https://github.com/PikadudeNo1/gulp-svelte/commit/33e01a77f2a2847653eec240e49b5d7eb4d8231b) I'll send a PR once I've updated the tests.

**Comment by adonespitogo** [comment]
any update on this?

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-svelte/pull/4#issuecomment-353817058

**Comment by shinnn** [comment]
If there is no progress on https://github.com/sveltejs/svelte/issues/1055 in the next few months, I'll just drop support for IIFE/UMD modules and close this issue.
