### ISSUE TITLE
Support preprocess

### ISSUE THREAD

**Issue by Cleecanth** [shinnn/gulp-svelte#8]
As far as I can tell, there's no way to preprocess using this plugin. Just wondering, is there a technical limitation or a suggested workaround?

If the implementation could be like the [Svelte rollup plugin](https://github.com/rollup/rollup-plugin-svelte/), I'd certainly be willing to submit a PR.

**Comment by shinnn** [comment]
Implemented in v0.8.0. Thanks for the suggestion, @Cleecanth.
